---
configuration:
- key: "launchUrl"
  value: "https://projectportaltest.int.sap.hana.ondemand.com/"
- key: "ApplicationId"
  value: null
id: null
name: "Requirements"
artifactTypeId: "Document"
description:
  title: ""
  details: "Requirements document"
  icon: null
  background: null
  moreInfo: ""
  other: null
created: null
modified: null
features: null
application: null
source:
  url: null
  type: ""
